openapi: 3.0.3
info:
  title: Greeting Service
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /greeter/hello:
    get:
      summary: Say hello
      description: Greet a person by name
      tags:
        - greeting
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string

